### ISSUE TITLE
A quick “fork” that works out of the box with vue-quill-editor and Vue/Nuxt apps

### ISSUE THREAD

**Issue by aral** [patleeman/quill-markdown-shortcuts#10]
Hey @patleeman, just wanted to let you know that I made a quick and dirty fork that works in Vue/Nuxt (SSR) apps – and documented it at: https://github.com/aral/quill-markdown-shortcuts-for-vue-quill-editor

I also documented in the readme setup instructions as well as the issue I was seeing (“Quill is undefined” errors) and what I changed to work around it in (basically, importing Quill in the two module files and exporting the main file in ES6 format).

Just a quick heads up in case it helps in any way.

Thank you again for this module. It is an absolute gem.

**Comment by patleeman** [comment]
Hey @aral,

This is awesome. I'm a huge Vue.js fan and I fully support this!

I will add a link to the readme for people looking to use this module with Vue.
