### ISSUE TITLE
It should stop matching when typing in a code block

### ISSUE THREAD

**Issue by PeachScript** [patleeman/quill-markdown-shortcuts#11]
## Versions

The vue editor version from doc: https://github.com/aral/quill-markdown-shortcuts-for-vue-quill-editor

## What is expected?

This plugin stop matching when I typing in a code block.

## What is actually happened?

This plugin still work and replace some code like `/* comment message */`.

## How to reproduce it?

Open the [live example](https://patleeman.github.io/quill-markdown-shortcuts/) of doc, and create a code block through ` ``` `，then try to type `/* */`.

Almost forgot, thanks for your great plugin!

**Comment by aral** [comment]
Can confirm that this is also an issue with the main repo (https://patleeman.github.io/quill-markdown-shortcuts/)

**Comment by PeachScript** [comment]
Hello @patleeman , I have been create a PR to fix this problem, could you check it?

**Comment by patleeman** [comment]
@PeachScript Thanks for putting this together!

I forgot to add this instruction to the readme, but can you do a `npm install` and `npm run build` to compile the built assets as well? That will generate a new dist/markdownShortcuts.js with your changes.

Great work and thanks for pulling this PR together.

**Comment by patleeman** [comment]
Oh and @aral is the one who is managing the vue component repository.

**Comment by PeachScript** [comment]
@patleeman that's OK, I've updated, and @aral could you sync changes to your repository from upstream?

**Comment by patleeman** [comment]
Merged, thanks @PeachScript

**Comment by PeachScript** [comment]
My pleasure @patleeman
