### ISSUE TITLE
Support for pasting markdown

### ISSUE THREAD

**Issue by philippkuehn** [patleeman/quill-markdown-shortcuts#17]
Would be nice if pasted markdown would be converted.

**Comment by park53kr** [comment]
@philippkuehn 
I was inspired by this issue. So I made a module converting pasted markdown to formatted text.
I really appreciate if you find a bug and report. 
[Link](https://github.com/park53kr/quill-markdown-toolbar)

**Comment by patleeman** [comment]
Awesome solution @morishjs. Thanks.
