### ISSUE TITLE
Ending blockquote

### ISSUE THREAD

**Issue by vishim** [patleeman/quill-markdown-shortcuts#18]
Entering a newline does not end blockquote. There seems to be no way to end a blockquote.
This is a bug. 

![blockquote](https://user-images.githubusercontent.com/5598054/42151769-e87d46c0-7dd5-11e8-88c8-252c025ba75e.gif)

**Comment by wrobbinz** [comment]
@vishim This issue isn't specific to this module. You can confirm by reproducing this bug @ [on a standard quilljs instance](https://quilljs.com/standalone/full/). I believe a relevant issue to follow would be: https://github.com/quilljs/quill/issues/1977
