### ISSUE TITLE
Selection is null

### ISSUE THREAD

**Issue by laurensiusadi** [patleeman/quill-markdown-shortcuts#19]
I get this error often when showing quill editor with content inside (instantiating editor with content from DB). But I don't get the error when it's already instantiated (normal usage)

![firefox_2018-07-20_11-28-57](https://user-images.githubusercontent.com/5661040/42983352-6b7ef6ca-8c10-11e8-8ce1-35c743cccb0b.png)

**Comment by patleeman** [comment]
This should have been fixed in https://github.com/patleeman/quill-markdown-shortcuts/commit/1ffa027679a9dbc976203a16980969fc975f2d31. If not please open a new issue.
