### ISSUE TITLE
bold and italic on the same line breaks

### ISSUE THREAD

**Issue by xdamman** [patleeman/quill-markdown-shortcuts#6]
This looks like a very cool plugin.
Running into a few annoying issues though that prevent me from using this on prod:

On the demo: https://patleeman.github.io/quill-markdown-shortcuts/

If you type 
```
**bold** *italic*
```
It will turn the entire line into italic.
Also, unable to get out of a fenced code block. Even after clicking on remove all styles.

See:
![](https://d.pr/free/i/Zl96sJ+)

**Comment by patleeman** [comment]
Thanks for pointing these out, I will take a look at these corner cases

**Comment by patleeman** [comment]
Oh this is interesting, it doesn't happen if you hit enter but it does if you hit space.

**Comment by patleeman** [comment]
Looking at these discussions:

https://github.com/quilljs/quill/issues/1228

https://github.com/quilljs/quill/issues/954

It seems like Quill's removeFormat doesn't clear block formats without a selected range.
